<?php

/*
 * This file is part of ibrand/groupon.
 *
 * (c) iBrand <https://www.ibrand.cc>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace iBrand\Component\Groupon\Test;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Orchestra\Testbench\TestCase;

/**
 * Class BaseTest
 * @package iBrand\Component\Groupon\Test
 */
abstract class BaseTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var $grouponRepository
     */
    public $grouponRepository;

    /**
     * @var $grouponItemRepository
     */
    public $grouponItemRepository;

    /**
     * set up test.
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->loadMigrationsFrom(__DIR__.'/database');

        $this->grouponRepository = $this->app->make(\iBrand\Component\Groupon\Repositories\GrouponRepository::class);

        $this->grouponItemRepository = $this->app->make(\iBrand\Component\Groupon\Repositories\GrouponItemRepository::class);

        $this->seedGoods();
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     */
    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver' => 'sqlite',
            'database' => ':memory:',
        ]);
        $app['config']->set('repository.cache.enabled', true);

        $app['config']->set('ibrand.groupon', require __DIR__.'/../config/groupon.php');
        $app['config']->set('ibrand.groupon.models.goods', Goods::class);
    }

    /**
     * @param $app
     */
    protected function loadMigrationsFrom($app)
    {
        $this->artisan('migrate', ['--database' => 'testing']);
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            \Prettus\Repository\Providers\RepositoryServiceProvider::class, \Orchestra\Database\ConsoleServiceProvider::class, \iBrand\Scheduling\ServiceProvider::class, \iBrand\Component\Groupon\GrouponServiceProvider::class,
        ];
    }

    /**
     * seed some goods.
     */
    public function seedGoods()
    {
        //Goods::create([]);
    }
}
